### ISSUE TITLE
How to use? 

### ISSUE THREAD

**Issue by JokersCat** [24hoster/Discord-Token-Generator#1]
Is this a simple showcase what you would get when you buy or what is this? I only can see that you get the cookie and the fingerprint but from where you will get the captcha?

**Comment by 24hoster** [comment]
> Is this a simple showcase what you would get when you buy or what is this? I only can see that you get the cookie and the fingerprint but from where you will get the captcha?


Hello, add my discord therefore you will be redirected to a demonstration video.

**Comment by JokersCat** [comment]
Can you give me your discord tag?

**Comment by 24hoster** [comment]
> Can you give me your discord tag?

24 HOST#2344
